重现问题：配置Nginx反向代理的时候 如果代理目标地址是本服务器其他服务器的时候【也就是端口不同】会存在本地环会问题，导致目标地址请求报错。

错误日志：

    cn.hutool.core.io.IORuntimeException: NoRouteToHostException: No route to host (Host unreachable)
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:1098) ~[hutool-all-5.4.0.jar!/:na]
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:942) ~[hutool-all-5.4.0.jar!/:na]
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:913) ~[hutool-all-5.4.0.jar!/:na]
        at com.bot.task.CheckPayOrderService.check(CheckPayOrderService.java:51) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:558) ~[na:na]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:277) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342) ~[na:na]
        at cn.hutool.http.HttpConnection.getOutputStream(HttpConnection.java:449) ~[hutool-all-5.4.0.jar!/:na]
        at cn.hutool.http.HttpRequest.sendFormUrlEncoded(HttpRequest.java:1121) ~[hutool-all-5.4.0.jar!/:na]
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:1090) ~[hutool-all-5.4.0.jar!/:na]
        ... 16 common frames omitted
